# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa66d4879bcaf5db0a58644c025c37c5927d132bde8d659542ce980a5c04e34f365dd746dea674bdb1359ba2dbcec1837d1824bcbb56d49ee399654c86103eb7

test:
  secret_key_base: 6d2133c4de5ee36355abc4f9e46b3c318436c49744f02086611e2a7115f2864c983d6ce317a30b8d3ee54c19e3339699a33efe0710cbf2b45abe0fe61c10c9ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
